### ISSUE TITLE
something which Exception in thread "main" java.lang.Exception

### ISSUE THREAD

**Issue by cristicmf** [FISCO-BCOS/fisco-package-build-tool#22]
[root@nodetaiping test_node]# ./node_manager.sh all
Exception in thread "main" java.lang.Exception
	at org.bcos.channel.client.Service.run(Service.java:242)
	at org.bcos.contract.tools.SystemContractTools.main(SystemContractTools.java:50)

**Comment by JimmyShi22** [comment]
此处我们会添加更友好的错误提示
